exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
]

line-length = 128
indent-width = 4

target-version = "py313"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]

allowed-confusables = ["ρ", "×", "–", "γ"]

select = [
  "A", "E",  "F",  "B",
  "S", "COM", "C4", "EXE", "ICN", "PIE", "PLR1714", "ARG",
  "PERF",  "FURB",  "PLE",  "TRY002",  "W",  "UP",  "RUF", "SIM", "NPY",
# "D", # later TODO
# "FIX", "TD", # later TODO
]
ignore = [
"UP031",    # format TODO
"NPY002",   # random
"E741",     # ambiguous variable name
"E501",     # line length
]

preview = true

extend-select = ["DOC"]
extend-ignore = [
  "E265", # no-space-after-block-comment TODO
# pathlib
  "FURB101", "FURB103",
# whitespaces
  "E201", "E202", "E203", "E211",
  "E221", "E222", "E225", "E226", "E227", "E228",
  "E231", "E241", "E271", "E272",
]

[lint.per-file-ignores]
"src/get_matrices_C.py" = ["COM819"]  # prohibited-trailing-comma
"src/libs/tmap.py"      = ["E251"]    # unexpected-spaces-around-keyword-parameter-equals
