all:
	make -f fortran_makefile
	make -f get_matrices_makefile
	make -f npy2dat_makefile
	make -f regression_makefile
clean:
	make clean -f fortran_makefile
	make clean -f get_matrices_makefile
	make clean -f npy2dat_makefile
	make clean -f regression_makefile

