all:
	make -f get_matrices_makefile
	make -f npy2dat_makefile
	make -f regression_makefile
	make -f prediction_makefile
clean:
	make clean -f get_matrices_makefile
	make clean -f npy2dat_makefile
	make clean -f regression_makefile
	make clean -f prediction_makefile

